In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
# One-hot encoding categorical columns
dataset = pd.get_dummies(dataset, drop_first=True)


In [5]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [6]:
dataset=dataset.drop("User ID",axis=1)

In [7]:
dataset["Purchased"].value_counts() # Here we have to count the o's and 1's 
#Here we can check this BALANCED/IMBALANCED?
#If Balanced Dataset = It'll be in Equal numbers for both 0 & 1
# If Imbalanced = Deviations will be there.
# Unique Entries using .value_counts() method

Purchased
0    257
1    143
Name: count, dtype: int64

In [8]:
indep=dataset[['Age','EstimatedSalary','Purchased','Gender_Male']]
dep=dataset["Purchased"]

In [9]:
indep.shape

(400, 4)

In [10]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [11]:
# SPlit into training set and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [12]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train) #HERE ITSELF THE MODEL GOT CREATED
y_pred=classifier.predict(X_test) #test the model here
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)
print(cm)


              precision    recall  f1-score   support

           0       0.95      0.95      0.95        85
           1       0.92      0.92      0.92        49

    accuracy                           0.94       134
   macro avg       0.94      0.94      0.94       134
weighted avg       0.94      0.94      0.94       134

[[81  4]
 [ 4 45]]


In [13]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train,y_train) #HERE ITSELF THE MODEL GOT CREATED
y_pred=classifier.predict(X_test) #test the model here
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        85
           1       1.00      1.00      1.00        49

    accuracy                           1.00       134
   macro avg       1.00      1.00      1.00       134
weighted avg       1.00      1.00      1.00       134

[[85  0]
 [ 0 49]]


In [14]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train,y_train) #HERE ITSELF THE MODEL GOT CREATED
y_pred=classifier.predict(X_test) #test the model here
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        85
           1       1.00      1.00      1.00        49

    accuracy                           1.00       134
   macro avg       1.00      1.00      1.00       134
weighted avg       1.00      1.00      1.00       134

[[85  0]
 [ 0 49]]


In [15]:
from sklearn.naive_bayes import CategoricalNB
classifier = CategoricalNB()
classifier.fit(X_train,y_train) #HERE ITSELF THE MODEL GOT CREATED
y_pred=classifier.predict(X_test) #test the model here
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        85
           1       1.00      1.00      1.00        49

    accuracy                           1.00       134
   macro avg       1.00      1.00      1.00       134
weighted avg       1.00      1.00      1.00       134

[[85  0]
 [ 0 49]]


In [16]:
from sklearn.naive_bayes import ComplementNB
classifier = ComplementNB()
classifier.fit(X_train,y_train) #HERE ITSELF THE MODEL GOT CREATED
y_pred=classifier.predict(X_test) #test the model here
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        85
           1       1.00      1.00      1.00        49

    accuracy                           1.00       134
   macro avg       1.00      1.00      1.00       134
weighted avg       1.00      1.00      1.00       134

[[85  0]
 [ 0 49]]


In [ ]:
y_pred=classifier.predict(X_test)

In [ ]:
# With the above steps we usually do the r_score value in the Regression Algorithms
# So instead we can use "CONFUSION MATRIX"

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [ ]:
print(cm)

In [ ]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)

In [ ]:
print(clf_report)

In [ ]:
# What we are seeing is perfect classification (100% accuracy, precision, recall, and F1-score).
# So, That’s why all values are 1.00.

In [ ]:
# If our model got the good performance then we can save the model and send it to the deployment.

In [ ]:
#Save our model 
import pickle
filename="finalized_model_knn_classification.sav" # file name has been created.

In [ ]:
# Here we have to insert the already created model.
pickle.dump(classifier,open(filename,'wb')) # Here the 'wb' is "Write Binary".

# With this we have saved the model.

In [ ]:
# Next step is to load the saved model.
loaded_model=pickle.load(open("finalized_model_knn_classification.sav",'rb'))
#Here we have to check with the user input in real time.
result=loaded_model.predict([[15624510, 1, 19, 19000]])

In [ ]:
result